# Generated by Django 5.2.6 on 2025-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
