# Generated by Django 5.2.6 on 2025-09-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('UZS', "so'm"), ('RUB', '₽'), ('USD', '$')], default='UZS', max_length=3),
        ),
    ]
