# Generated by Django 5.2.6 on 2025-09-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_price_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
