# Generated by Django 5.2.6 on 2025-09-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
